name: tap_books
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  flutter_dotenv: ^5.1.0
  flutter_gemini: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  google_generative_ai: ^0.4.4
  lottie: ^3.1.2
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/messages.json
    - .env
