name: tap_books
description: "Smart Book Insights with Gemini."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.7.7
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  flutter_dotenv: ^5.1.0
  flutter_gemini: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  flutter_svg: ^2.0.10+1
  google_generative_ai: ^0.4.4
  lottie: ^3.1.2
  splash_view: ^2.0.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/animations/
    - assets/messages.json
    - .env
  
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        style: italic
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
