// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpKAsMxqGkG0j-l2TmRecevyPPTJ7kAVg',
    appId: '1:257869758671:web:dc98f0f51be3992aa937ba',
    messagingSenderId: '257869758671',
    projectId: 'tapbooks-ad97a',
    authDomain: 'tapbooks-ad97a.firebaseapp.com',
    storageBucket: 'tapbooks-ad97a.appspot.com',
    measurementId: 'G-JWTD83CXBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ju0hOw1npQhrISQ5wJzi5NxDnKmV8zM',
    appId: '1:257869758671:android:e7badb0eb189f240a937ba',
    messagingSenderId: '257869758671',
    projectId: 'tapbooks-ad97a',
    storageBucket: 'tapbooks-ad97a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUpyzMjZsAzUt4V9Jvvd8kzpgJ93j66s',
    appId: '1:257869758671:ios:b15fae99c334e483a937ba',
    messagingSenderId: '257869758671',
    projectId: 'tapbooks-ad97a',
    storageBucket: 'tapbooks-ad97a.appspot.com',
    iosClientId: '257869758671-l01jdivla2lbf556inds1epdm9apd4p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapBooks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUpyzMjZsAzUt4V9Jvvd8kzpgJ93j66s',
    appId: '1:257869758671:ios:b15fae99c334e483a937ba',
    messagingSenderId: '257869758671',
    projectId: 'tapbooks-ad97a',
    storageBucket: 'tapbooks-ad97a.appspot.com',
    iosClientId: '257869758671-l01jdivla2lbf556inds1epdm9apd4p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapBooks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpKAsMxqGkG0j-l2TmRecevyPPTJ7kAVg',
    appId: '1:257869758671:web:5806e8e676d62d35a937ba',
    messagingSenderId: '257869758671',
    projectId: 'tapbooks-ad97a',
    authDomain: 'tapbooks-ad97a.firebaseapp.com',
    storageBucket: 'tapbooks-ad97a.appspot.com',
    measurementId: 'G-MQRLHG2NJ6',
  );
}
